### ISSUE TITLE
Docs / web layout issue for "Your first project" in Firefox 

### ISSUE THREAD

**Issue by jcbeck37** [typescene/typescene.github.io#1]
Steps to Reproduce

1. Open the latest Firefox browser (67.0.4 at time of report)
2. Visit https://typescene.dev/docs/guides/first
3. Maximized window. Zoom is 100% original. Resolution is 1920x1080. (OS = Windows; scaling is 150%).

Expected Result
1. Rendered layout should look the same as what you see in Chrome

Actual Result
1. Rendered layout has float/overlap issues.

**Comment by jcormont** [comment]
Thanks I'll look into this when I'm back at my PC. This might have something to do with overflowing code in the pre blocks...?

**Comment by jcbeck37** [comment]
No problem - petty issue but distracting from your project! I attempted to edit the flex-box settings and the pre styles/overflow in Firefox dev tools, but was not able to get the columns to sit next to each other. I'm not up to speed on flex box. Good luck!

**Comment by jcormont** [comment]
Turns out it was a known 'issue' where Firefox is working correctly while Chrome isn't. Fixed now. Thanks again!
